### PR TITLE
Fix / save media on old android

### LINKED ISSUE #1324: saved images don't show up in gallery
Long pressing on an image in the timeline and selecting "save" option should make the picture show up in the gallery app, but it does not.
A toast saying "Media file added to gallery" shows up.

Tested on LineageOS 16.0 with Simple Gallery and LOS stock gallery.

play store v0.19.0

Relates to #973 and PR #1242

### LINKED ISSUE #1578: File isn't downloaded when another file with the same name already exists
```
RiotX version: v0.22.0
Android version: 9 / Lineage 16.0
```

RiotX does not download a file if their already exists another one with the same name in the riotx download folder. I get a notification that the new file was downloaded but only the old exists one on my device

### PR DESCRIPTION
**Pull request by BillCarsonFr**
Fixes save attachement issues on pre Q
I'll need some older devices to test the gallery update

Fixes #1578
Fixes #1324

Change log 
- File isn't downloaded when another file with the same name already exists (#1578)
 - saved images don't show up in gallery (#1324)

### CODE REVIEW

File: vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt [hunk 1]
```diff
@@ -1357,6 +1354,11 @@ class RoomDetailFragment @Inject constructor(
     }
 
     private fun onSaveActionClicked(action: EventSharedAction.Save) {
+        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q &&
```
Comment (bmarty) [inline vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt:1357]:
```suggestion
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q
```

File: vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt [hunk 2]
```diff
@@ -1357,6 +1354,11 @@ class RoomDetailFragment @Inject constructor(
...
+                !checkPermissions(PERMISSIONS_FOR_WRITING_FILES, this, SAVE_ATTACHEMENT_REQUEST_CODE)) {
```
Comment (bmarty) [inline vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt:1358]:
```suggestion
                && !checkPermissions(PERMISSIONS_FOR_WRITING_FILES, this, SAVE_ATTACHEMENT_REQUEST_CODE)) {
```

**Comment by duncanturk** [comment]
I can confirm that this fixes #1324 on Android 9/LineageOS 16.0
