### PR TITLE
Fix issue with image orientation

### LINKED ISSUE #517: Picture uploads are unreliable, pictures are shown in wrong aspect ratio on desktop client
Every time I send a picture on RiotX, I hold my breath. Often times they time out, and then messages and pictures are sent out of order. Yesterday, a picture upload was marked "canceled" (with no option for me to do anything about it) and then started flitting between "timed out" and continuing to upload. It finally succeeded, but is a stretched, blurry mess when I view it from the web client.

### PR DESCRIPTION
**Pull request by bmarty**
Attempt to fix #517

### CODE REVIEW

File: vector/src/main/java/im/vector/riotx/core/images/ImageTools.kt [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+import android.database.Cursor
+import android.net.Uri
+import android.provider.MediaStore
+import androidx.exifinterface.media.ExifInterface
+import timber.log.Timber
+import javax.inject.Inject
+import javax.inject.Singleton
+
+@Singleton
+class ImageTools @Inject constructor(private val context: Context) {
```
Comment (ganfra) [inline vector/src/main/java/im/vector/riotx/core/images/ImageTools.kt]: No need to have scope @Singleton: there is no state and no heavy init

File: vector/src/main/java/im/vector/riotx/core/di/VectorComponent.kt [hunk 2]
```diff
@@ -67,6 +68,8 @@ interface VectorComponent {
 
     fun dimensionConverter(): DimensionConverter
 
+    fun imageTools(): ImageTools
```
Comment (ganfra) [inline vector/src/main/java/im/vector/riotx/core/di/VectorComponent.kt]: As you remove scope, you won't need to be exposed here neither

File: vector/src/main/java/im/vector/riotx/core/images/ImageTools.kt (hunk 1 above)
Comment (bmarty) [reply vector/src/main/java/im/vector/riotx/core/images/ImageTools.kt]: ok, done
