### PR TITLE
WIP /  Fix Copying link from a message shouldn't open context menu

### LINKED ISSUE #364: Copying link from a message shouldn't open context menu
When holding down on a link in a message, Riot X successfully copies only that link (this is amazing!).

However, it also opens the context menu (View Source, Add reaction, etc). Ideally this would not pop up if it detected you were copying only part of the message.

### LINKED ISSUE #365: Link-in-message copy should have more meaningful toast message
Currently when copying a link from a message, the toast is "Copied to clipboard". At this point I'm not sure if the whole message was copied or just the link.

It would be nice to changed the message to "Copied link to clipboard".

### PR DESCRIPTION
**Pull request by BillCarsonFr**
Fixes #364
Fixes #365

### CODE REVIEW

File: vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/MessageTextItem.kt [hunk 1]
```diff
@@ -40,14 +40,26 @@ abstract class MessageTextItem : AbsMessageItem<MessageTextItem.Holder>() {
...
     private val mvmtMethod = BetterLinkMovementMethod.newInstance().also {
         it.setOnLinkClickListener { _, url ->
             //Return false to let android manage the click on the link, or true if the link is handled by the application
             urlClickCallback?.onUrlClicked(url) == true
         }
-        it.setOnLinkLongClickListener { _, url ->
+        it.setOnLinkLongClickListener { tv, url ->
             //Long clicks are handled by parent, return true to block android to do something with url
-            urlClickCallback?.onUrlLongClicked(url) == true
+            (urlClickCallback?.onUrlLongClicked(url) == true).also {
```
Comment (bmarty) [inline vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/MessageTextItem.kt]: A `if` is maybe better than `also` for code clarity?

File: vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/MessageTextItem.kt [hunk 2]
```diff
@@ -40,14 +40,26 @@ abstract class MessageTextItem : AbsMessageItem<MessageTextItem.Holder>() {
...
+                //pervent textview long click to be triggered
```
Comment (bmarty) [inline vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/MessageTextItem.kt]: to prevent from + verb with ing :)

File: vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/MessageTextItem.kt [hunk 3]
```diff
@@ -40,14 +40,26 @@ abstract class MessageTextItem : AbsMessageItem<MessageTextItem.Holder>() {
...
+                if (it) {
+                    val current = tv.getTag(R.id.messageTextView)
```
Comment (bmarty) [inline vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/MessageTextItem.kt]: is it the only solution to use a view tag?

**Comment by bmarty** [comment]
Please do not forget to auto-assign issue you're working on (#364 here)
