### PR TITLE
Feature/fix version

### LINKED ISSUE #1442: Error when handling /version responses
Response to /versions:
1.  [r0.5.0, r0.6.0] works
2.  [r0.5.0, r0.6.1] doesn't work
3.  [r0.6.0] doesn't work

If 1. works, I would expect 2. to work too, because it's just a minor version upgrade. [Servers have to send only the latest minor version.](https://matrix.org/docs/spec/client_server/unstable#get-matrix-client-versions).

### PR DESCRIPTION
**Pull request by bmarty**
Fixes #1442 

With this change, the fact that homeserver sends a list of versions is reduced to checking the latest version it supports.

So maybe this is not right to do that, I do not know.

Anyway I think it is OK.

### CODE REVIEW

File: matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/version/HomeServerVersion.kt [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+        internal fun parse(value: String): HomeServerVersion? {
+            val result = pattern.matchEntire(value) ?: return null
+            return HomeServerVersion(
+                    major = result.groupValues[1].toInt(),
+                    minor = result.groupValues[2].toInt(),
+                    patch = result.groupValues[3].toInt()
+            )
+        }
+
+        val r0_0_1 = parse("r0.0.1")!!
```
Comment (ganfra) [inline matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/version/HomeServerVersion.kt:52]: Is it really necessary to use parsing here?

Comment (bmarty) [reply matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/version/HomeServerVersion.kt]: No, I've change it, thanks. Also mini version is now `r0.0.0` (instead of `r0.0.1`)
