### PR TITLE
Crashes when private key missing

### LINKED ISSUE #1337: Verify Manually by text crashes if private SSK not known
https://github.com/matrix-org/riot-android-rageshakes/issues/10675

### PR DESCRIPTION
**Pull request by BillCarsonFr**
Fixes  #1337

### CODE REVIEW

**Comment by michel-slm** [comment]
Nice issue number too

File: vector/src/main/java/im/vector/riotx/features/settings/devices/DevicesViewModel.kt [hunk 1]
```diff
@@ -215,8 +216,13 @@ class DevicesViewModel @AssistedInject constructor(
     private fun handleVerifyManually(action: DevicesAction.MarkAsManuallyVerified) = withState { state ->
         viewModelScope.launch {
             if (state.hasAccountCrossSigning) {
-                awaitCallback<Unit> {
-                    tryThis { session.cryptoService().crossSigningService().trustDevice(action.cryptoDeviceInfo.deviceId, it) }
```
Comment (bmarty) [inline vector/src/main/java/im/vector/riotx/features/settings/devices/DevicesViewModel.kt:219]: tryThis can return null, why the compiler was not complaining?
