### PR TITLE
Fix threading issues while restoring keys backup.

### LINKED ISSUE #526: Restore keys backup with pwd is broken
Reported in room RiotX: https://matrix.to/#/!tTIucwUZLRtKnXeurb:matrix.org/$15670254341295UuvcH:ostavrosnika.com?via=matrix.org&via=privacytools.io&via=feneas.org

### PR DESCRIPTION
**Pull request by onurays**
Fixes #526

### CODE REVIEW

File: matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/actions/MegolmSessionDataImporter.kt [hunk 1]
```diff
@@ -46,19 +45,14 @@ internal class MegolmSessionDataImporter @Inject constructor(private val olmDevi
...
         val totalNumbersOfKeys = megolmSessionsData.size
         var lastProgress = 0
         var totalNumbersOfImportedKeys = 0
 
-        if (progressListener != null) {
-            uiHandler.post {
-                progressListener.onProgress(0, 100)
-            }
-        }
+        progressListener?.onProgress(0, 100)
```
Comment (bmarty) [inline matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/actions/MegolmSessionDataImporter.kt]: Could you please add in the Javadoc of [ProgressListener](https://github.com/vector-im/riotX-android/blob/15dc4d6369834b3f1a219152a41422685c97f65f/matrix-sdk-android/src/main/java/im/vector/matrix/android/api/listeners/ProgressListener.kt#L27) that the method will not be called on the UI thread.

Also it can be worth to add the info in the file CHANGES.md, in the section `SDK API changes`
